### PR TITLE
[#152] Implement Notification card

### LINKED ISSUE #152: Implement notification card component
**Is your feature request related to a problem? Please describe.**

A notifications card component is required so that users can navigate to a notification page and see any outstanding unread notifications on their account. The notification should be informative and concise.

**Describe the solution you'd like**

A notification card component should be created as according to the figma design mocks. The component should display the relevant users URL, username, handle, notification text and the time it was received. 
To achieve this the component should take in the above listed information as props as well an a link that can navigate the user to whatver the notifcation is displaying.

**Describe alternatives you've considered**
There are not really any alternative solutions for this feature except for in terms of designing.

**Additional context**
This issue was discussed, approved and allocated by the front-end team at a team meeting on 24/03/22

image

### PR DESCRIPTION
**Pull request by arathibiju**
# Description:
Please provide a summary of changes made and the relevant issue that has been worked on. Also list any major changes made to project structure/dependencies if applicable

Fixes #152. This PR introduces the NotificationCard component which is to be used in the notification screen in the future. It takes in all the information displayed as props and is responsive for mobile screens. 
 A screenshot of this component is shown below.

image

A sample usage of this component is as follows 
```javascript
<NotificationCard
  description="This user liked your post"
  time="3 hours ago"
  handle="testusername"
  username="TheTestUser"
  image={`https://assets1.ignimgs.com/2020/11/06/walle---blogroll-1604651447059.jpg?width=1280`}
/>

```

### All Submissions:

* [X] Have you followed the guidelines in our [Contributing document](../CONTRIBUTING.md)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] My code follows the code style of this project
- [X] My code has been commented
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by the1e — APPROVED** [review]
Great work! LGTM :)

**Review by dogeliness — APPROVED** [review]
Notification card looks great!

**Review by shreytailor — APPROVED** [review]
LGTM! Nit: shall we change the directory name of the component to `notificationcard` (same as the component)?

**Comment by arathibiju** [comment]
> LGTM! Nit: shall we change the directory name of the component to `notificationcard` (same as the component)?

Good call! I've pushed the new changes

**Review by uoa-lzha989 — APPROVED** [review]
LGTM

**Comment by the1e** [comment]
The update with the View and Controller design structure looks great!

**Review by scorpionknifes — APPROVED** [review]

**Review by sv-s-dev — APPROVED** [review]
Looks good!

**Pull request merged**
