### PR TITLE
[#133] Fix typo in LandingView.jsx

### LINKED ISSUE #133: Fix typo on landing page
**Describe the bug**
Landing page is missing an apostrophe.

**To Reproduce**
1. Run `npm start` in `frontend/`
2. Observe landing page

**Expected behavior**
An apostrophe should be added, such that the sentence becomes  "Check out what's going on in the world right now."

The relevant string is in src/pages/landing/LandingView.jsx

**Screenshots**
image

### PR DESCRIPTION
**Pull request by hmit106**
# Description:
Adds an apostrophe in the correct spot on the landing page.

Also applies latest ESLint formatting to LandingView.jsx

Closes #133 

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](../CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] My code follows the code style of this project
- [ ] My code has been commented
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by hmit106** [comment]
No idea why the diff thinks I've changed the whole file rather than just the text in the div, I'll see if I can fix

Edit - it's because this file never had ESLint applied to it after the indent size was changed :|

**Review by harristomy — APPROVED** [review]
Looks good

**Comment by seanhogunkim** [comment]
>

**Review by seanhogunkim — APPROVED** [review]
Looks fine, maybe we should do a global lint regarding your comment about the indents? Or if it's not a big deal we can just ignore it, since people should easily be able to deal with it case by case

**Comment by harristomy** [comment]
> 

Yea this will be one of the very last issues to do, so that the global lint refactor doesn't affect other open PR's before we handover the project

**Pull request merged**
